{
 "title": "Notes API — Requests & Errors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "My App",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"myapp\"}"
    }
   ]
  },
  {
   "title": "База данных",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_health_status * on(instance, job) up{job=\"myapp\"}"
    }
   ]
  },
  {
   "title": "Запросов за 1 минуту",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 5, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Warnings (4xx) за 1 минуту",
   "type": "stat",
   "gridPos": { "x": 13, "y": 0, "w": 5, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_warnings_total[1m]))"
    }
   ]
  },
  {
   "title": "Errors (5xx) за 1 минуту",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_errors_total[1m]))"
    }
   ]
  },
  {
   "title": "Запросы по статусам",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Warnings и Errors",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_warnings_total[1m]))",
     "legendFormat": "Warnings (4xx)"
    },
    {
     "expr": "sum(rate(http_errors_total[1m]))",
     "legendFormat": "Errors (5xx)"
    }
   ]
  }
 ]
}